"""add listing image column to listings table

Revision ID: 03d8d705e142
Revises: 9a0cc8030f6c
Create Date: 2026-06-15 02:23:27.342715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d8d705e142'
down_revision = '9a0cc8030f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_product_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_product_listing', schema=None) as batch_op:
        batch_op.drop_column('listing_image')

    # ### end Alembic commands ###
