"""Add order cards and messaging fields

Revision ID: 66b3ac08a00b
Revises: 708b315557fd
Create Date: 2026-08-11 02:08:36.139490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b3ac08a00b'
down_revision = '708b315557fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity_kg', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('order_buyer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])
        batch_op.create_foreign_key(None, 'farm_product_listing', ['listing_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['buyer_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_buyer_id_fkey'), 'buyer_profile', ['buyer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')
        batch_op.drop_column('quantity_kg')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('msg_type')

    # ### end Alembic commands ###
