"""add farm profile and grower buyer models

Revision ID: b0ca7927a8d9
Revises: d5e562ee71c3
Create Date: 2026-04-10 07:22:12.517469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0ca7927a8d9'
down_revision = 'd5e562ee71c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('farm_size_acres', sa.Float(), nullable=True),
    sa.Column('altitude_masl', sa.Integer(), nullable=True),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farm_product_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('varietal', sa.String(length=100), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=True),
    sa.Column('roast_level', sa.String(length=30), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('minimum_order_kg', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('tasting_notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm_profile.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grower_buyer_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('grower_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('agreed_price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mpesa_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['grower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['farm_product_listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_available')
        batch_op.drop_column('product_type')

    op.drop_table('grower_buyer_transaction')
    op.drop_table('farm_product_listing')
    op.drop_table('farm_profile')
    # ### end Alembic commands ###
