"""Modifies GrowerBuyerTransaction table

Revision ID: fe8130fc4b82
Revises: eebcf30a8a56
Create Date: 2026-06-03 10:55:13.947399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8130fc4b82'
down_revision = 'eebcf30a8a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_product_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grower_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['grower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_product_listing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grower_id')

    # ### end Alembic commands ###
